# Основы *линейной алгебры*
## Работа с векторами и матрицами

In [57]:
import numpy as np
import random as rand
import scipy.linalg as lp

In [58]:
empty_list = [] # создание пустого списка (медленный)
base_list_zeroes = [0] * 5 # создание списка заполненного нулями
base_list1 = [1, 2, 3, 4, 5]
base_list2 = [[1,2,3], [4,5,6], [7,8,9]]

print(base_list1)
print(base_list2)

[1, 2, 3, 4, 5]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [59]:
def f1(x):
    return x*x

projection_map = map(f1, base_list1)
for i in projection_map:
    print(i)
print(" ")
projection_list = list(map(np.sin, base_list1))
print(projection_list)

projection_list_lamda = list(map(lambda x: x*x, base_list1))
projection_list

1
4
9
16
25
 
[0.8414709848078965, 0.9092974268256817, 0.1411200080598672, -0.7568024953079282, -0.9589242746631385]


[0.8414709848078965,
 0.9092974268256817,
 0.1411200080598672,
 -0.7568024953079282,
 -0.9589242746631385]

In [60]:
XX = np.array([1,2,3,4,5])
print(XX)
print(" ")
YY = np.array([[1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5]])
print(YY)
print(" ")
AA = np.arange(1, 10, 2)
print(AA)
print(" ")
ZZ = np.linspace(1, 10, 8)
print(ZZ)

[1 2 3 4 5]
 
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
 
[1 3 5 7 9]
 
[ 1.          2.28571429  3.57142857  4.85714286  6.14285714  7.42857143
  8.71428571 10.        ]


## Алгебра матриц

### Умножение матрицы на ветор

In [61]:
def Matrix2Vector(A, a):
    A = np.array(A)
    n,m = np.shape(A) # раскладываем кортеж
    b = [0] * n
    for i in range(0, n): # Для всех строк матрицы рассчитываем ячейки вектора результата
        semi = 0
        for j in range(0, n): # Номер элемента в строке
            semi += A[i][j] * a[j]
        b[i] = semi
    return b

pow_res = Matrix2Vector(base_list2, base_list1)
pow_res
    


[14, 32, 50]

## Транспонирование матрицы

In [62]:
def Transpose(A):
    A = np.array(A)
    B = np.array(A)
    n,m = np.shape(A)

    
    for i in range(0, n):
        for j in range(0, m):
            B[j][i] = A[i][j]

    return B

base_transposed = Transpose(base_list2)
base_transposed

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## Умножение матрицы на матрицу

In [64]:
def Matrix2Matrix(A, B):
    la = np.shape(A)
    lb = np.shape(B)

    C = []
    for i in range(0, lb[1]):
        C.append([0] * la[0])

    for i in range(0, la[0]):
        for j in range(0, lb[1]):
            semi = 0
            for k in range(0, la[1]):
                semi += A[i][k] * B[k][j]
            C[i][j] = semi
            
    return np.array(C)

A = np.array([[1,2,3], [4,5,6], [7,8,9]])
C = Matrix2Matrix(A, A.T)
C

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [66]:
def Triangle(A):
    M = np.array(A)
    n, m = np.shape(A)

    d = 1
    rank = min(n, m)

    # треугольный вид 
    # обработать случай когда на главной диагонали нули
    # обратная матрица

    return M, d, rank