In [336]:
import numpy as np
import random as rand
import scipy.linalg as lp

In [337]:
def f(u):
    return 1 / (1 + np.exp(-u))

def f1(u):
    return f(u)

def Y(X, W, O, func):
    return func(W@X+O)

In [338]:
XX = np.array([[0],
               [1]])
WW1 = np.array([[1.0, 0.5], 
                [-1.0, 2.0]])
WW2 = np.array([1.5, -1])
OO1 = np.array([[1],
                [1]])
OO2 = np.array([1])

print("XX=", XX, "\n")
print("WW1=", WW1, "\n")
print("WW2=", WW2, "\n")
print("OO1=", OO1, "\n")
print("OO2=", OO2, "\n")

UU1 = np.dot(WW1,XX) + OO1
print("\nUU1=", UU1, "\n")
YY1 = f(UU1)
print("YY1=", YY1, "\n")

UU2 = np.dot(WW2, YY1) + OO2
print("\nUU1=", UU2, "\n")
YY2 = f(UU2)
print("YY1=", YY2, "\n")


XX= [[0]
 [1]] 

WW1= [[ 1.   0.5]
 [-1.   2. ]] 

WW2= [ 1.5 -1. ] 

OO1= [[1]
 [1]] 

OO2= [1] 


UU1= [[1.5]
 [3. ]] 

YY1= [[0.81757448]
 [0.95257413]] 


UU1= [1.27378759] 

YY1= [0.78139043] 



In [351]:
def Topology(InpCount, NeurCount, func): # Количество входов, список из количества нейронов в каждом слое (количество слоев --- длина списка), спискок функций для каждого слоя (пока одна функция)
    #[{f1, W1, O1, X1, Y1}, {f2, W2, O2, X2, Y2}, ....]
    topology = []
    for i in range(len(NeurCount)):
        WW = np.random.rand(NeurCount[i], InpCount)
        OO = np.ones((NeurCount[i],1))
        XX = np.ones((NeurCount[i],1))
        YY = np.ones((NeurCount[i],1))
        topology.append([func, WW, OO, XX, YY])
    
    return topology
    
    # print(OO)
    # W = [] + [np.random.randn(i-1, i) for i in range(1, len(NeuronsCount))]
    # print(W)
    # O = [np.ones((NeuronsCount[)) for i in range(len(NeuronsCount))]

res = Topology(2, [2,1], f)

for i in range(len(res)):
    print(res[i])
    print("\n")


def Topology(Inp, NN):
    seed = 13
    topology = []
    for i in range(len(NN)):
        WW = np.random.rand(NN[i], Inp)
        OO = np.ones((NeurCount[i],1))
        XX = np.ones((NeurCount[i],1))
        YY = np.ones((NeurCount[i],1))
        topology.append([func, WW, OO, XX, YY])
    
    return topology
    
#Должна вернуть список кортежей вида [{f, W1, O1, Y1}, {f, W2, O2, Y2}, ....]
# W - random -1 до 1
# O - единицы
# X, Y - забить нулями

[<function f at 0x000001E1C2C02840>, array([[0.54835402, 0.43438843],
       [0.6602736 , 0.39072173]]), array([[1.],
       [1.]]), array([[1.],
       [1.]]), array([[1.],
       [1.]])]


[<function f at 0x000001E1C2C02840>, array([[0.32927051, 0.95446369]]), array([[1.]]), array([[1.]]), array([[1.]])]




In [340]:
def TestGirl(XX):
    WW1 = np.array([[3.281, 3.661, -3.682], 
                [-1.425, -3.18, 0.248]])
    WW2 = np.array([9.97, -1.537])
    OO1 = np.array([[-0.13],
                [1.336]])
    OO2 = np.array([-3.783])

    # print("XX=", XX, "\n")
    # print("WW1=", WW1, "\n")
    # print("WW2=", WW2, "\n")
    # print("OO1=", OO1, "\n")
    # print("OO2=", OO2, "\n")

    UU1 = np.dot(WW1,XX) + OO1
    # print("\nUU1=", UU1, "\n")
    YY1 = f(UU1)
    # print("YY1=", YY1, "\n")

    UU2 = np.dot(WW2, YY1) + OO2
    # print("\nUU1=", UU2, "\n")
    YY2 = f(UU2)
    # print("YY1=", YY2, "\n")

    return YY2


    

In [341]:
XX1 = np.array([[1],
               [-1],
               [1]])

XX2 = np.array([[1],
               [1],
               [-1]])

XX3 = np.array([[1],
               [-1],
               [-1]])

res1 = TestGirl(XX1)
print("1) Res= ", res1)

res2 = TestGirl(XX2)
print("2) Res= ", res2)

res3 = TestGirl(XX3)
print("3) Res= ", res3)

1) Res=  [0.00594712]
2) Res=  [0.99785487]
3) Res=  [0.98704813]


Обучение нейройнной сети

In [342]:
N1 = 3 # количество входов 1 слой
M1 = 2 # количество выходов (нейронов) 1 слой

N2 = M1 # количество входов 2 слой
M2 = 1 # количество выходов (нейронов) 2 слой

def f(u): # функция активации
    return 1 / (1 + np.exp(-u))

def df(u): # производная функции активации
    return np.exp(-u) / ((1 + np.exp(-u))*(1 + np.exp(-u)))

def f1(u): # функция активации первого слоя
    return f(u)

def f2(u): # функция активации второго слоя
    return f(u)

W1 = np.random.randn(M1, N1)
print("W1=", W1)
O1 = np.random.randn(M1, 1)
print("O1=", O1)

W2 = np.random.randn(M2, N2)
print("W2=", W1)
O2 = np.random.randn(M2, 1)
print("O1=", O2)




W1= [[ 0.07460177  1.72175023 -0.58244239]
 [ 1.12307649 -1.39134016 -1.61928501]]
O1= [[-1.25760118]
 [-0.44960128]]
W2= [[ 0.07460177  1.72175023 -0.58244239]
 [ 1.12307649 -1.39134016 -1.61928501]]
O1= [[0.45577201]]


In [343]:
# Обучение сети
ro = 0.5 # скорость обучения (from 0 to 1]

Примеры обучения

In [344]:
# перебор всех входных вариантов
XX1 = np.array([[-1],   # квартира
               [-1],    # красивый
               [1]])    # Тяж. рок

XX2 = np.array([[-1],
               [-1],
               [-1]])

XX3 = np.array([[-1],
               [1],
               [1]])

XX4 = np.array([[-1],
               [1],
               [-1]])

XX5 = np.array([[1],
               [-1],
               [1]])

XX6 = np.array([[1],
               [-1],
               [-1]])

XX7 = np.array([[1],
               [1],
               [1]])

XX8 = np.array([[1],
               [1],
               [-1]])

# то, что нужно получить по итогу
YY1 = np.array([0])
YY2 = np.array([0])
YY3 = np.array([1])
YY4 = np.array([1])
YY5 = np.array([1])
YY6 = np.array([0])
YY7 = np.array([1])
YY8 = np.array([1])

# Первая веха обучения
### Обратное распространение ошибки

In [345]:
Y_out = YY1
X_in = XX1
# расчёт ошибки по выходу сети - метод прямого распространения

U1 = np.dot(W1,X_in) + O1
print("U1=", U1, "\n")
Y1 = f(U1)
print("Y1=", Y1, "\n")
U2 = np.dot(W2, Y1) + O2
print("U2=", U2, "\n")
Y2 = f(U2)
print("Y2=", Y2, "\n")
ErrSize = Y_out - Y2
print("Размер ошибки: ", ErrSize)
grad = ErrSize * df(Y2)
print("Вектор градиента ошибки: ", grad)


U1= [[-3.63639558]
 [-1.80062262]] 

Y1= [[0.02567079]
 [0.14177529]] 

U2= [[0.48742699]] 

Y2= [[0.61950011]] 

Размер ошибки:  [[-0.61950011]]
Вектор градиента ошибки:  [[-0.14091678]]


Коррекция весов слоя

In [347]:
delta_W2 = ro * grad * Y1.T
print("delta_W2=", delta_W2)

delta_O2 = ro * grad
print("delta_O2=", delta_O2)

W2 = W2 + delta_W2
print("W2=", W2)

O2 = O2 + delta_O2
print("O2=", O2)


delta_W2= [[-0.00180872 -0.00998926]]
delta_O2= [[-0.07045839]]
W2= [[0.25879943 0.15578219]]
O2= [[0.31485523]]


In [348]:
# пересчёт ошибки на предыдущий слой

err1 = W2.T * grad
print(err1)

[[-0.03646918]
 [-0.02195233]]
